version: '3.8'
services:
  app:
    container_name: record_manager
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3001"
    depends_on:
      - surrealdb

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    command: start --log debug --auth --user root --pass root file://var/lib/surrealdb/record_manager_db.db
    ports:
      - "8000:8000"
    volumes:
      - ./data/database.db:/var/lib/surrealdb/record_manager_db.db
      - ./src/scripts:/docker-entrypoint-initdb.d
    restart: always

