version: '3.8'
services:
  label-manager-server:
    env_file: 
      - .env
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - label-manager-database

  label-manager-database:
    image: postgres
    env_file: 
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    env_file: 
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - label-manager-database
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DBNAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${METABASE_DBUSER}
      MB_DB_PASS: ${METABASE_DBPASS}
      MB_DB_HOST: label-manager-database

volumes:
  postgres-data:
    driver: local
