version: '3.8'
services:
  label-manager-server:
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "3001:3001"
    depends_on:
      - label-manager-database

  label-manager-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: DataBase123@
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    depends_on:
      - label-manager-database
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: DataBase123@
      MB_DB_HOST: label-manager-database

volumes:
  postgres-data:
    driver: local
