version: '1'
services:
  node: 
    build: .
    command: "npm run dev"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    expose:
      - "3001"
    ports:
      - "3001:3001"


